protein_analysis_django/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('protein_analysis_tool.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

protein_analysis_tool/urls.py
from django.urls import path

from . import views

app_name = 'protein_analysis_tool'

urlpatterns = [
    # url config for homepage/form
    path('', views.index_form_view, name='index'),

    # url config for displaying/processing queries
    path('process_query/', views.process_query_view, name='process-query'),

    # url config for processing all queries
    path('process_all_queries/', views.process_all_queries_view, name='process-all-queries'),

    # url config for displaying results
    path('results/<int:result_id>/', views.view_query_result, name='view-single-result'),
]

protein_analysis_tool/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage

from protein_analysis_django.settings import MEDIA_ROOT

fs = FileSystemStorage(location=MEDIA_ROOT)


class Collection(models.Model):
    """
    Collection name information and file storage.
    """
    collection_name = models.CharField(max_length=128)
    collection_file = models.FileField()
    collection_hash = models.CharField(max_length=16, unique=True)
    pub_date = models.DateTimeField('Date Published')
    collection_parsed = models.BooleanField(default=False)
    sequence_count = models.IntegerField(default=0)

    def __str__(self):
        return self.collection_name


class Sequence(models.Model):
    """
    Collection sequences.
    """
    collection_fk = models.ForeignKey(Collection, on_delete=models.CASCADE)
    sequence_id = models.CharField(max_length=256)
    sequence_name = models.CharField(max_length=256)
    sequence = models.CharField(max_length=4096)

    def __str__(self):
        return self.sequence_name


class Motif(models.Model):
    """
    Motif to search for in sequences.
    """
    motif = models.CharField(max_length=16)

    def __str__(self):
        return self.motif


class Query(models.Model):
    """
    Combination of Collection and Motif.
    """
    collection_fk = models.ForeignKey(Collection, on_delete=models.CASCADE)
    motif_fk = models.ForeignKey(Motif, on_delete=models.CASCADE)
    min_num_motifs_per_sequence = models.IntegerField()
    max_char_distance_between_motifs = models.IntegerField()
    query_is_finished = models.BooleanField(default=False)

    class Meta:
        unique_together = (
            'collection_fk',
            'motif_fk',
            'min_num_motifs_per_sequence',
            'max_char_distance_between_motifs',
        )

    def __str__(self):
        return '{collection} -> {motif}'.format(collection=self.collection_fk, motif=self.motif_fk)


class QuerySequence(models.Model):
    """
    Combination of Query and Sequence.
    """
    query_fk = models.ForeignKey(Query, on_delete=models.CASCADE)
    sequence_fk = models.ForeignKey(Sequence, on_delete=models.CASCADE)
    is_match = models.BooleanField(default=False)
    matches = models.CharField(max_length=4096)

    class Meta:
        unique_together = (
            'query_fk',
            'sequence_fk',
        )

    def __str__(self):
        return '{motif} -> {matches}'.format(motif=self.sequence_fk, matches=self.matches)

protein_analysis_tool/forms.py
from Bio import SeqIO
from django import forms
from django.utils import timezone

from .custom import large_file_hasher
from .models import Collection, Motif, Sequence

from django.core.files.storage import default_storage


class CollectionAdminForm(forms.ModelForm):
    class Meta:
        model = Collection
        fields = "__all__"

    def save(self, commit=True, *args, **kwargs):
        # Save without committing.
        # Creates object with name and file.
        collection = super(CollectionAdminForm, self).save(commit=False)

        if not default_storage.exists(collection.collection_file.path):
            default_storage.save(collection.collection_file.path, collection.collection_file)

        if not collection.pk:
            # Set fields.
            collection.pub_date = timezone.now()
            collection.collection_parsed = False
            collection.sequence_count = 0

            # Generate file hash.
            file_path = collection.collection_file.path
            collection_hash = large_file_hasher(file_path)

            # If file hash not found, save collection
            if Collection.objects.filter(collection_hash=collection_hash).count() == 0:
                collection.collection_hash = collection_hash
                collection.save()

        if collection.pk:
            if not collection.collection_parsed:
                for record in SeqIO.parse(collection.collection_file.path, 'fasta'):
                    sequence = Sequence.objects.create(
                        collection_fk=collection,
                        sequence_id=record.id,
                        sequence_name=record.name,
                        sequence=str(record.seq),
                    )
                    sequence.save()

                collection.collection_parsed = True
                collection.sequence_count = Sequence.objects.filter(collection_fk=collection).count()

            collection.save()

        return collection


class DefineParametersForm(forms.Form):
    min_num_motifs_per_sequence = forms.IntegerField(
        label='Minimum Number Of Motifs Per Sequence',
        min_value=3,
        max_value=10,
    )
    max_char_distance_between_motifs = forms.IntegerField(
        label='Maximum Character Distance Between Start And End Of Valid Motif Range',
        min_value=50,
        max_value=5000,
    )

protein_analysis_tool/views.py
from .views_controller import IndexFormController, ProcessQueryController, ResultsController


def index_form_view(request):
    """
    Connects to controller for displaying
    and processing motif analysis form.
    :param request:
    :return:
    """
    controller = IndexFormController(request)

    if request.method == 'POST':
        return controller.process_form()

    return controller.generate_form()


def process_query_view(request):
    """
    Connects to controller for displaying
    and processing commands to process queries.
    :param request:
    :return:
    """
    controller = ProcessQueryController(request)

    if request.method == 'POST':
        return controller.process_query()

    return controller.display_queries()


def process_all_queries_view(request):
    """
    Sends a command to process all queries.
    :param request:
    :return:
    """
    if request.method == 'POST':
        pass

    # Static method. Does not initialize an instance of controller.
    return ProcessQueryController.process_all_queries()


def view_query_result(request, result_id):
    """
    Connects to a controller to gather and display
    results for a specific query.
    :param request:
    :param result_id:
    :return:
    """
    controller = ResultsController(request)

    if request.method == 'POST':
        pass

    return controller.display_results(result_id)

protein_analysis_tool/templates/protein_analysis_tool/define_parameters.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Define Parameters{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <p class="lead">Protein Sequence Collections Selected For Motif Analysis</p>
        <div class="form-group">
            <ul class="list-group">
                {% for collection in collection_list %}
                    <div class="col-xs-4">
                        <li class="list-group-item">
                            {{ collection.collection_name }}
                            <span class="badge">{{ collection.sequence_count }}</span>
                        </li>
                    </div>
                {% endfor %}
            </ul>
        </div>

        <div class="clearfix"></div>
        <div class="top15"></div>

        <p class="lead">Motifs Selected For Protein Sequence Analysis</p>
        <div class="form-group">
            <ul class="list-group">
                {% for motif in motif_list %}
                    <div class="col-xs-4">
                        <li class="list-group-item">
                            {{ motif.motif }}
                        </li>
                    </div>
                {% endfor %}
            </ul>
        </div>

        <div class="clearfix"></div>

        <div class="top15"></div>
        <p class="lead">{% render_field form.min_num_motifs_per_sequence.label %}</p>
        {% render_field form.min_num_motifs_per_sequence  class+="form-control" %}

        <div class="top15"></div>
        <p class="lead">{% render_field form.max_char_distance_between_motifs.label %}</p>
        {% render_field form.max_char_distance_between_motifs class+="form-control" %}


        <div class="clearfix"></div>

        <div class="form-group top15">
            <button class="btn btn-block btn-primary" type="submit">Select Parameters</button>
        </div>
    </form>
{% endblock %}

protein_analysis_tool/templates/protein_analysis_tool/form_index.html
{% extends 'base.html' %}

{% block title %}Motif Analysis Tool{% endblock %}

{% block content %}
    <div class="bg-info" style="padding:15px;">
        <form method="post">
            {% csrf_token %}
            <h1>Motif Analysis Tool For Amino Acids</h1>
            <h3>University of St. Thomas - Houston Bioinformatics</h3>
            <ul class="nav nav-tabs top15">
                <li><a href="#copy_paste_fasta" data-toggle="tab">Copy/Paste FASTA</a></li>
                <li><a href="#select_curated_collections" data-toggle="tab">Select Curated Collection(s)</a></li>
            </ul>
            <div class="tab-content" id="tabs">
                <div class="tab-pane" id="copy_paste_fasta">
                    <div class="form-group">
                        <h4>Name the pasted FASTA collection.</h4>
                        <input class="form-control" type="text" name="sequence_data_title">
                        <div class="top15"></div>
                        <h4>Paste FASTA-format amino acid sequences (20,000 character max).</h4>
                        <textarea class="form-control" name="sequence_data" rows="10" style="resize:vertical;" maxlength="20000" wrap="soft"></textarea>
                    </div>
                </div>
                <div class="tab-pane" id="select_curated_collections">
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <h4>Select collections of amino acid sequences.</h4>
                            {% for collection in collection_list %}
                                <label class="checkbox-inline">
                                    <input type="checkbox" value="{{ collection.pk }}" name="selected_collections[]">
                                    {{ collection.collection_name }} <span class="badge">{{ collection.sequence_count }}</span>
                                </label>
                            {% endfor %}
                        </div>
                    </div>

                </div>
            </div>

            <div class="row">
                <div class="form-group col-xs-12">
                    <h4>Select motifs to search for in pasted sequences.</h4>
                    {% for motif in motif_list %}
                        <label class="checkbox-inline"><input type="checkbox" value="{{ motif.pk }}" name="selected_motifs[]">{{ motif.motif }}</label>
                    {% endfor %}
                </div>
            </div>

            <div class="row">
                <div class="col-xs-6">
                    <h4>Minimum motif match density.</h4>
                    <input type="number" class="form-control" name="min_num_motifs" placeholder="3" required>
                </div>
                <div class="col-xs-6">
                    <h4>Maximum range to group motif matches.</h4>
                    <input type="number" class="form-control" name="max_motif_range" placeholder="100" required>
                </div>
            </div>
            <button type="submit" class="btn btn-block btn-primary top15">Submit Query</button>
        </form>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        function activaTab(tab){
            $('.nav-tabs a[href="#' + tab + '"]').tab('show');
        }

        activaTab('copy_paste_fasta');
    </script>
{% endblock %}

protein_analysis_tool/templates/protein_analysis_tool/process_query.html
{% extends 'base.html' %}

{% block title %}Processing Query{% endblock %}

{% block content %}
    <p class="lead">Collection/Motif combos </p>
    <a class="btn btn-block btn-primary" href="{% url "protein_analysis_tool:process-all-queries" %}">Process All Queries</a>
    <ul class="list-group top30">
        {% for query in query_list %}
            <div class="col-xs-6">
                <li class="list-group-item">
                    <b>Collection:</b> {{ query.collection_fk }}<br>
                    <b>Motif:</b> {{ query.motif_fk }}<br>
                    <b>Motif Frequency:</b> {{ query.min_num_motifs_per_sequence }}<br>
                    <b>Motif Search Range:</b> {{ query.max_char_distance_between_motifs }}<br>
                    <b>Status:</b> {% if query.query_is_finished %}Finished{% else %}Not Finished{% endif %}<br>
                </li>
            </div>
            <div class="col-xs-6">
                    {% if query.query_is_finished %}
                        <div class="top30">
                            <a class="btn btn-block btn-primary" href="{% url "protein_analysis_tool:view-single-result" query.pk %}">View Results</a>
                        </div>
                    {% else %}
                        <form method="post">
                            {% csrf_token %}
                            <input type="hidden" name="query_id" value="{{ query.pk }}">
                            <div class="top30">
                                <button class="btn btn-block btn-default" type="submit">Process Query</button>
                            </div>
                        </form>
                    {% endif %}
                </div>

            <div class="clearfix"></div>
        {% endfor %}
    </ul>
{% endblock %}

protein_analysis_tool/templates/protein_analysis_tool/result_viewer.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}View Results{% endblock %}

{% block content %}
    <table class="table table-bordered table-responsive">
        <tr>
            <th>Sequence</th>
            <th>Motif</th>
            <th>Frequency</th>
            <th># Matches</th>
            <th>Detail View</th>
        </tr>
        {% for result in results %}
            <tr>
                <td>{{ result.0.sequence_fk.sequence_id }}</td>
                <td>{{ result.0.query_fk.motif_fk.motif }}</td>
                <td>{{ result.0.query_fk.min_num_motifs_per_sequence }} matches per {{ result.0.query_fk.max_char_distance_between_motifs }} AA</td>
                <td>{{ result.1}}</td>
                <td>
                    <button type="button" class="btn btn-block btn-default" data-toggle="modal"
                            data-target="#popin{{ result.0.sequence_fk.pk }}">View Details</button>

                    <div id="popin{{ result.0.sequence_fk.pk }}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">{{ result.0.sequence_fk.sequence_id }}</h4>
                                </div>
                                <div class="modal-body">
                                    <table class="table table-responsive">
                                        <tr>
                                            <th>Sequence</th>
                                        </tr>
                                        <tr>
                                            <td class="sequence-view is-breakable">
                                                {{ result.0.sequence_fk.sequence }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>Matches</th>
                                        </tr>
                                        {% for match in result.0.matches %}
                                            {% if match|length >= result.0.query_fk.min_num_motifs_per_sequence %}
                                            <tr>
                                                <td onmouseover="highlightRange({{ match.0.span.0 }}, {{ result.0.query_fk.max_char_distance_between_motifs }})">{{ match }}</td>
                                            </tr>
                                            {% endif %}
                                        {% endfor %}
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </table>
    <div class="center-pagination">
        {% if results.has_other_pages %}
            <ul class="pagination">
                {% if results.has_previous %}
                    <li><a href="?page={{ results.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in results.paginator.page_range %}
                    {% if results.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if results.has_next %}
                    <li><a href="?page={{ results.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>

{% endblock %}

{% block javascript %}
    <script src="{% static 'protein_analysis_tool/js/jquery.mark.min.js' %}"></script>
    <script>
        // function for marking motif
        $(document).ready(function(){
            $(".sequence-view").markRegExp(/{{ motif }}/gmi, {className: "match"});
        });

        function highlightRange(startPos, range) {
            $(".sequence-view").markRanges([{
                start: parseInt(startPos),
                length: parseInt(range)
            }], {className: "matchRange"})
        }
    </script>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %} | UST Motif Analysis Tool</title>
        <link rel="stylesheet" type="text/css" href="{% static 'protein_analysis_tool/css/bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'protein_analysis_tool/css/custom.css' %}">
    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#protein_analysis_tool_navbar" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'protein_analysis_tool:index' %}">UST Motif Analysis Tool</a>
                </div>
                <div class="collapse navbar-collapse" id="protein_analysis_tool_navbar">
                    <ul class="nav navbar-nav">
                        <!-- Links go here -->
                        <li><a href="{% url 'protein_analysis_tool:process-query' %}">View Queries</a></li>
                        <li><a href="#">Create Motif</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'admin:index' %}">Admin Login</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- /Navbar -->

        <div class="container">
            <div class="col-xs-12">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
        </div>
        <!-- Load Javascript -->
        <script src="{% static 'protein_analysis_tool/js/jquery-3.2.1.js' %}"></script>
        <script src="{% static 'protein_analysis_tool/js/bootstrap.js' %}"></script>
        <!-- /Load Javascript -->
        {% block javascript %}{% endblock %}
    </body>
</html>